name: Build and Deploy API

on:
  push:
    branches:
    - master
    paths:
    - api/**
    - devops/**

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-18.04
    env:
      REGISTRY: 'us-central1-docker.pkg.dev/cloudmade-sandbox'
      REPOSITORY: toptal
      IMAGE: api
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # Authenticate to GCP
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Login to Artifact Registry
      - run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build and Push Docker image 
      - name: Build, tag, and push image to Artifact Registry
        id: build-image
        run: |
          cd api
          docker build -t $REGISTRY/$REPOSITORY/$IMAGE:$IMAGE_TAG -t $REGISTRY/$REPOSITORY/$IMAGE:latest .
          docker push $REGISTRY/$REPOSITORY/$IMAGE:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY/$IMAGE:latest

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'toptal-cluster'
          location: 'us-central1-a'

      - name: Deploy to GKE
        id: 'deploy-gke'
        run: |
          kubectl set image deployment/api api=$IMAGE:$IMAGE_TAG
          kubectl rollout status deployment/api